name: Build-ios

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build (e.g. update22-9-0)"
        required: true
        default: update22-9-0

env:
  SCCACHE_GHA_ENABLED: 'true'

permissions:
  contents: read

jobs:
  build-ios:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: macos-15-xlarge, target_arch: arm64, xcode: 16.4 }
          - { os: macos-15-xlarge, target_arch: arm64-simulator, xcode: 16.4 }
          - { os: macos-15-xlarge, target_arch: x64-simulator, xcode: 16.4 }

    runs-on: ${{ matrix.config.os }}
    env:
      TARGET_ARCH: ${{ matrix.config.target_arch }}
      XCODE_VERSION: ${{ matrix.config.xcode }}

    steps:
      - name: Free Disk Space
        run: |
          echo "Before cleanup:"
          df -h

          sudo rm -rf /Library/Frameworks/Mono.framework
          sudo rm -rf /Library/Frameworks/Xamarin.iOS.framework
          sudo rm -rf /Library/Frameworks/Xamarin.Android.framework
          sudo rm -rf /Users/runner/Library/Android
          sudo rm -rf /usr/local/share/powershell
          sudo find /Applications -type d -name "Xcode_*.app" ! -name "Xcode_$XCODE_VERSION.app" -prune -exec rm -rf "{}" \;

          # Remove Android SDK & NDK
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/local/Caskroom/android-sdk
          sudo rm -rf /usr/local/Caskroom/android-ndk
          sudo rm -rf "$ANDROID_HOME" || true
          sudo rm -rf "$ANDROID_SDK_ROOT" || true

          # Remove Homebrew caches
          sudo rm -rf /Users/runner/Library/Caches/Homebrew
          sudo rm -rf /usr/local/Homebrew/Library/Taps

          # Remove unused package managers
          sudo rm -rf /usr/local/share/dotnet
          sudo rm -rf /usr/local/lib/node_modules
          sudo rm -rf /opt/hostedtoolcache/CodeQL

          echo "After cleanup:"
          df -h

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.6

      - name: Xcode Select Version
        uses: mobiledevops/xcode-select-version-action@v1
        with:
          xcode-select-version: ${{ matrix.config.xcode }}

      # Python 3.12 (chosen by configure.py) doesn't have support for distutils
      # https://github.com/nodejs/node-gyp/issues/2869 workaround
      - name: Build
        run: |
          python3.12 -m venv .
          source bin/activate
          python3.12 -m pip install setuptools
          ./tools/ios_framework_prepare.sh $TARGET_ARCH

      - uses: actions/upload-artifact@v4
        with:
          name: node-ios-${{ env.TARGET_ARCH }}
          path: out_ios_${{ env.TARGET_ARCH }}

  combine-ios:
    strategy:
      matrix:
        config:
          - { os: macos-15-xlarge, xcode: 16.4 }
    runs-on: ${{ matrix.config.os }}
    needs: build-ios
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Xcode Select Version
        uses: mobiledevops/xcode-select-version-action@v1
        with:
          xcode-select-version: ${{ matrix.config.xcode }}

      - uses: actions/download-artifact@v4
        with:
          pattern: node-ios-*
          merge-multiple: true
          path: out_ios

      # Python 3.12 (chosen by configure.py) doesn't have support for distutils
      # https://github.com/nodejs/node-gyp/issues/2869 workaround
      - name: Generate config.gypi
        run: |
          python3.12 -m venv .
          source bin/activate
          python3.12 -m pip install setuptools
          ./configure

      - name: Combine
        run: |
          python3.12 -m venv .
          source bin/activate
          python3.12 -m pip install setuptools
          ./tools/ios_framework_prepare.sh combine_frameworks
          mkdir -p artifacts/include
          cp -R out_ios/NodeMobile.xcframework artifacts/
          ./tools/copy_libnode_headers.sh ios
          cp -R out_ios/libnode/include/* artifacts/include

      - uses: actions/upload-artifact@v4
        with:
          name: nodejs-mobile-ios
          path: artifacts

      - uses: geekyeggo/delete-artifact@v5
        with:
          name: node-ios-*
